### ISSUE TITLE
Panic `depth shouldn't be greater than 1`

### ISSUE THREAD

**Issue by qarmin** [mindeng/nom-exif#20]
Code
```
fn check_file(path: &str) {
    let content = match fs::read(&path) {
        Ok(content) => content,
        Err(e) => {
            println!("{e}");
            return;
        }
    };
    println!("Checking file: {path}");

    let mut parser = MediaParser::new();

    // Parse unseekable
    let reader = Cursor::new(&content);
    let Ok(ms) = MediaSource::unseekable(reader) else {
        return ;
    };
    let iter: Result<ExifIter, _> = parser.parse(ms);
    if let Ok(iter) = iter {
        let _ = iter.parse_gps_info();
        for i in iter {
            let s = i;
            s.tag_code();
            s.get_value();
            let _ = s.get_result();
            s.tag();
            s.ifd_index();
            s.has_value();
        }
    }

    let reader = Cursor::new(&content);
    let Ok(ms) = MediaSource::unseekable(reader) else {
        return ;
    };
    let _: Result<TrackInfo, _> = parser.parse(ms);

    // Parse seekable
    let reader = Cursor::new(&content);
    let Ok(ms) = MediaSource::seekable(reader) else {
        return ;
    };
    let iter: Result<ExifIter, _> = parser.parse(ms);
    if let Ok(iter) = iter {
        let _ = iter.parse_gps_info();
        for i in iter {
            let s = i;
            s.tag_code();
            s.get_value();
            let _ = s.get_result();
            s.tag();
            s.ifd_index();
            s.has_value();
        }
    }

    let reader = Cursor::new(&content);
    let Ok(ms) = MediaSource::seekable(reader) else {
        return ;
    };
    let _: Result<TrackInfo, _> = parser.parse(ms);
}
```
panics here
```
Checking file: /opt/BROKEN_FILES_DIR/neg_x_IDX_54_RAND_997958133402232438691987_minimized_419.jpg
sub-ifd: ExifOffset
sub-ifd: ExifOffset

thread 'main' panicked at /home/runner/.cargo/git/checkouts/nom-exif-cf4dd29e16c043e1/1f5b02f/src/exif/travel.rs:148:13:
depth shouldn't be greater than 1
stack backtrace:
   0: rust_begin_unwind
             at /rustc/b8c8287a229cd79604aa84c25e1235fc78cd5f2e/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/b8c8287a229cd79604aa84c25e1235fc78cd5f2e/library/core/src/panicking.rs:75:14
   2: core::panicking::panic_display
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:273:5
   3: nom_exif::exif::travel::IfdHeaderTravel::travel_ifd::panic_cold_display
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panic.rs:100:13
   4: nom_exif::exif::travel::IfdHeaderTravel::travel_ifd
             at /home/runner/.cargo/git/checkouts/nom-exif-cf4dd29e16c043e1/1f5b02f/src/exif/travel.rs:148:13
   5: nom_exif::exif::travel::IfdHeaderTravel::travel_ifd
             at /home/runner/.cargo/git/checkouts/nom-exif-cf4dd29e16c043e1/1f5b02f/src/exif/travel.rs:169:13
   6: nom_exif::exif::travel::IfdHeaderTravel::travel_ifd
             at /home/runner/.cargo/git/checkouts/nom-exif-cf4dd29e16c043e1/1f5b02f/src/exif/travel.rs:169:13
   7: nom_exif::exif::extract_exif_with_mime
             at /home/runner/.cargo/git/checkouts/nom-exif-cf4dd29e16c043e1/1f5b02f/src/exif.rs:163:13
   8: nom_exif::exif::extract_exif_range
             at /home/runner/.cargo/git/checkouts/nom-exif-cf4dd29e16c043e1/1f5b02f/src/exif.rs:85:30
   9: nom_exif::exif::parse_exif_iter::{{closure}}
             at /home/runner/.cargo/git/checkouts/nom-exif-cf4dd29e16c043e1/1f5b02f/src/exif.rs:76:9
  10: nom_exif::parser::BufParser::load_and_parse::{{closure}}
             at /home/runner/.cargo/git/checkouts/nom-exif-cf4dd29e16c043e1/1f5b02f/src/parser.rs:166:30
  11: nom_exif::parser::BufParser::load_and_parse_with_offset
             at /home/runner/.cargo/git/checkouts/nom-exif-cf4dd29e16c043e1/1f5b02f/src/parser.rs:187:23
  12: nom_exif::parser::BufParser::load_and_parse
             at /home/runner/.cargo/git/checkouts/nom-exif-cf4dd29e16c043e1/1f5b02f/src/parser.rs:164:9
  13: nom_exif::exif::parse_exif_iter
             at /home/runner/.cargo/git/checkouts/nom-exif-cf4dd29e16c043e1/1f5b02f/src/exif.rs:75:22
  14: <nom_exif::exif::exif_iter::ExifIter as nom_exif::parser::ParseOutput<R,S>>::parse
             at /home/runner/.cargo/git/checkouts/nom-exif-cf4dd29e16c043e1/1f5b02f/src/parser.rs:299:9
  15: nom_exif::parser::MediaParser::do_parse
             at /home/runner/.cargo/git/checkouts/nom-exif-cf4dd29e16c043e1/1f5b02f/src/parser.rs:449:19
  16: nom_exif::parser::MediaParser::parse
             at /home/runner/.cargo/git/checkouts/nom-exif-cf4dd29e16c043e1/1f5b02f/src/parser.rs:438:19
  17: nom_exif::check_file
             at ./src/crates/nom_exif/src/main.rs:45:37
  18: nom_exif::main
             at ./src/crates/nom_exif/src/main.rs:24:9
  19: core::ops::function::FnOnce::call_once
             at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

##### Automatic Fuzzer note, output status "None", output signal "Some(6)"
```

[compressed.zip](https://github.com/user-attachments/files/17620313/compressed.zip)

**Comment by mindeng** [comment]
Got it! I’ll find time to analyze it as soon as possible! Thank you for your feedback!
